# Generated by Django 4.1.5 on 2023-01-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=300)),
                ('chapter', models.CharField(max_length=500)),
                ('problem', models.TextField()),
            ],
        ),
    ]
