# Generated by Django 4.1.7 on 2023-06-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_problems_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problems',
            name='book',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='problems',
            name='chapter',
            field=models.TextField(default='', max_length=500),
        ),
    ]
