# Generated by Django 4.1.7 on 2023-06-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_problems_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default='', upload_to='projectPics')),
                ('title', models.TextField(default='')),
                ('disc', models.TextField(default='')),
                ('codeUrl', models.TextField(default='')),
                ('demoUrl', models.TextField(default='')),
            ],
        ),
    ]
