# Generated by Django 4.1.7 on 2023-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userLang', models.TextField(max_length=200)),
                ('userInput', models.TextField()),
                ('userCode', models.TextField()),
            ],
        ),
    ]
