# Generated by Django 4.1.7 on 2023-06-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_alter_compiler_usercode_alter_compiler_userinput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiler',
            name='userInputType',
            field=models.TextField(default='1value'),
        ),
    ]
