# Generated by Django 4.1.7 on 2023-06-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_compiler_userinputtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiler',
            name='userInputType',
            field=models.TextField(default=''),
        ),
    ]
