# Generated by Django 4.1.7 on 2023-06-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_alter_compiler_userinputtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiler',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
